import React, { useState, useEffect } from "react";
import { Project, Category, DailyLog, ReportTemplate } from "@/src/lib/firebase";
import { getDailyLogs, getTemplates, saveTemplate } from "@/src/services/db";
import { generateSiteReport } from "./PdfGenerator";
import { FileText, Download, Palette, Settings2, Table, Layout, Save, CheckCircle2 } from "lucide-react";
import { motion } from "motion/react";
import { cn } from "@/src/lib/utils";

interface ReportsProps {
  projects: Project[];
  categories: Category[];
}

export default function Reports({ projects, categories }: ReportsProps) {
  const [options, setOptions] = useState({
    title: "Site Daily Log Report",
    subtitle: "Progress summary across all construction sites",
    footer: "Generated by Al-injaz Electric - Report Management System",
    theme: "Modern Blue" as any,
    includeLogs: true,
  });

  const [templates, setTemplates] = useState<ReportTemplate[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [saveStatus, setSaveStatus] = useState<string | null>(null);

  useEffect(() => {
    loadTemplates();
  }, []);

  const loadTemplates = async () => {
    const data = await getTemplates();
    setTemplates(data);
  };

  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
      const logsMap: Record<string, DailyLog[]> = {};
      if (options.includeLogs) {
        await Promise.all(projects.map(async (p) => {
          logsMap[p.id] = await getDailyLogs(p.id);
        }));
      }
      generateSiteReport(projects, categories, logsMap, options);
    } catch (err) {
      console.error(err);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSaveTemplate = async () => {
    const name = prompt("Enter a name for this template:");
    if (!name) return;

    try {
      await saveTemplate({
        name,
        headerTitle: options.title,
        headerSubtitle: options.subtitle,
        footerText: options.footer,
        theme: options.theme,
        visibleColumns: [] // Placeholder
      });
      loadTemplates();
      setSaveStatus("Saved!");
      setTimeout(() => setSaveStatus(null), 2000);
    } catch (err) {
      alert("Failed to save template");
    }
  };

  const applyTemplate = (t: ReportTemplate) => {
    setOptions({
      title: t.headerTitle,
      subtitle: t.headerSubtitle,
      footer: t.footerText,
      theme: t.theme,
      includeLogs: true
    });
  };

  return (
    <div className="grid md:grid-cols-3 gap-8">
      <div className="md:col-span-2 space-y-6">
        <section className="bg-white rounded-3xl p-6 border border-gray-100 shadow-sm space-y-6">
          <div className="flex items-center space-x-2 text-gray-900 border-b border-gray-50 pb-4">
             <Settings2 size={24} className="text-blue-500" />
             <h2 className="text-xl font-black">Report Configuration</h2>
          </div>

          <div className="space-y-4">
            <div className="space-y-1">
              <label className="text-[10px] font-black uppercase text-gray-400">Header Title</label>
              <input 
                type="text" 
                className="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"
                value={options.title}
                onChange={e => setOptions(o => ({ ...o, title: e.target.value }))}
              />
            </div>
            <div className="space-y-1">
              <label className="text-[10px] font-black uppercase text-gray-400">Subtitle</label>
              <input 
                type="text" 
                className="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"
                value={options.subtitle}
                onChange={e => setOptions(o => ({ ...o, subtitle: e.target.value }))}
              />
            </div>
            <div className="space-y-1">
              <label className="text-[10px] font-black uppercase text-gray-400">Footer Text</label>
              <textarea 
                className="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-2 h-20 outline-none focus:ring-2 focus:ring-blue-500 resize-none"
                value={options.footer}
                onChange={e => setOptions(o => ({ ...o, footer: e.target.value }))}
              />
            </div>
          </div>

          <div className="pt-4 border-t border-gray-50">
            <label className="text-[10px] font-black uppercase text-gray-400 mb-2 block">Visual Theme</label>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
              {["Modern Blue", "Sunshine", "Noir Gold", "Classic"].map((t) => (
                <button
                  key={t}
                  onClick={() => setOptions(o => ({ ...o, theme: t as any }))}
                  className={cn(
                    "px-3 py-4 rounded-2xl border text-xs font-bold transition-all",
                    options.theme === t 
                      ? "border-blue-500 bg-blue-50 text-blue-700 ring-2 ring-blue-500/20" 
                      : "border-gray-100 hover:bg-gray-50 text-gray-500"
                  )}
                >
                  {t}
                </button>
              ))}
            </div>
          </div>

          <div className="flex items-center space-x-3 pt-4 border-t border-gray-50">
             <input 
              type="checkbox" 
              id="includeLogs" 
              className="w-5 h-5 accent-blue-500 rounded-lg"
              checked={options.includeLogs}
              onChange={e => setOptions(o => ({ ...o, includeLogs: e.target.checked }))}
            />
             <label htmlFor="includeLogs" className="text-sm font-bold text-gray-700 cursor-pointer">
               Include daily logs in report
             </label>
          </div>
        </section>
      </div>

      <div className="space-y-6">
        <div className="bg-slate-900 rounded-3xl p-6 text-white shadow-xl shadow-slate-900/20 flex flex-col items-center text-center space-y-4">
           <div className="w-16 h-16 bg-blue-500/20 text-blue-400 rounded-full flex items-center justify-center mb-2">
             <FileText size={32} />
           </div>
           <div>
             <h3 className="text-lg font-bold">Generate PDF</h3>
             <p className="text-slate-400 text-sm mt-1">Export your site logs as a professionally formatted PDF report.</p>
           </div>
           
           <button 
            disabled={isGenerating}
            onClick={handleGenerate}
            className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-4 rounded-2xl flex items-center justify-center space-x-2 transition-all disabled:opacity-50"
           >
             <Download size={20} />
             <span>{isGenerating ? "Processing..." : "Download Report"}</span>
           </button>

           <button 
             onClick={handleSaveTemplate}
             className="w-full bg-slate-800 hover:bg-slate-700 text-slate-300 font-bold py-3 rounded-2xl border border-slate-700 flex items-center justify-center space-x-2 transition-all"
           >
             <Save size={18} />
             <span>{saveStatus || "Save Template"}</span>
           </button>
        </div>

        <section className="bg-white rounded-3xl p-6 border border-gray-100 shadow-sm space-y-4">
           <h3 className="text-sm font-black text-gray-400 uppercase tracking-widest">My Saved Templates</h3>
           <div className="space-y-2">
             {templates.length > 0 ? templates.map((t) => (
               <button 
                key={t.id}
                onClick={() => applyTemplate(t)}
                className="w-full text-left p-3 rounded-xl border border-gray-50 hover:border-blue-200 hover:bg-blue-50 transition-all flex items-center justify-between group"
               >
                 <div>
                   <p className="font-bold text-gray-800 text-sm truncate">{t.name}</p>
                   <p className="text-[10px] text-gray-400 font-medium">{t.theme}</p>
                 </div>
                 <Layout size={16} className="text-gray-300 group-hover:text-blue-500" />
               </button>
             )) : (
                <p className="text-xs text-gray-400 italic py-4">No templates saved yet.</p>
             )}
           </div>
        </section>
      </div>
    </div>
  );
}
